language: node_js
node_js:
  - '16.13.1'
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - sudo apt-get update -qq && sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
install:
  - npm install
