language: node_js
deploy:
  provider: npm
  email: michael.heuberger@binarykitchen.com
  api_key:
    secure: UGZ63W4+ATPrcUAFTiHYrIKpmCL6KL74mq/8zztdNTxweD5Zdy4SWlE3ch0iN4zUrDzMzoWmp9tUQVST+X0cgftRT43v/sRm08sULvRerUs20C2bPltILWFc43EaAKNafUIgIWCnyHlYl74QvTF3vrxQ0nQz8WHopBDvT3ceEuU=
  on:
    repo: binarykitchen/canvas-to-buffer
