language: node_js
deploy:
  provider: npm
  email: michael.heuberger@binarykitchen.com
  api_key:
    secure: QklltGgo1szC2Y3P9Izf2iJpAU4pQUys16umxtzTWgj65foN58KSxCvK644/eM1K4C5gcLu37B7GfzhBpa0CM97HUnvwbnKpTxgiYicBr1dT8dw0k7oLCABLt7EfqMQcP7nCpM7zNjmEKsakBPbkPB9smcjwah+II9MBXYFFthA=
  on:
    repo: binarykitchen/canvas-to-buffer
